name: SimplePlugin
main: io.github.lambo993.SimplePlugin
version: 0.4.9
authors: [Lambo993]
description: This is a very simple plugins.
commands:
  ignite:
    description: Set a player on fire.
    aliases: [lighter]
    usage: /<command> <player> <seconds>
  freeitem:
    description: Gives you a free item!
    aliases: [freegift]
    usage: /<command> [item]
  healthy:
    description: Heals you or the given player.
    aliases: [morehealth]
    usage: /<command> [player]
  Generateblock:
    description: Generate dirt block on top of you!
    aliases: [Blockgenerate]
    usage: /<command> [block]
  rule:
    description: Show the rules.
    aliases: [simplerule]
  echo:
    description: Echo the last thing you said
    aliases: [repeat]
    usage: /<command> [msg]
  pm:
    description: Private messages someone
    aliases: [privatemsg]
    usage: /<command> <player> [message]

permisssions:
  simpleplugin.*:
    description: Gives access to all test commands!
    default: op