WelcomeMessage: Welcome to the server! please follow the rules, to view the rules do /rule
rules:
  - Be respectful
  - Don't advertise
  - Play Fair
  - Don't ask for ranks
explosion:
  power: 10.0
  fire: false
operatorjoinmsg: Operator %operator% joined the game.