WelcomeMessage: '&6Welcome to the server! please follow the rules, to view the rules do &r/rule'
rules:
  - Be respectful
  - Don't advertise
  - Play Fair
  - Don't ask for ranks
explosion:
  power: 10.0
  fire: false
operatorjoinmsg: '&6Operator&4 %operator% &6joined the game.'