name: SimplePlugin
main: io.github.lambo993.SimplePlugin
version: 0.5.3
authors: [Lambo993, mahmoudnaruto96]
description: This is a very simple plugins.
commands:
  simpleplugin:
    description: Reloads simpleplugin.
    usage: /<command> <help/reload/version>
  ignite:
    description: Set a player on fire.
    aliases: [lighter]
    usage: /<command> <player> <seconds>
  freeitem:
    description: Gives you a free item!
    aliases: [freegift]
    usage: /<command> <itemname> [amount]
  healthy:
    description: Heals you or the given player.
    aliases: [morehealth]
    usage: /<command> [player]
  generateblock:
    description: Generate a block on top of you!
    aliases: [Blockgenerate]
    usage: /<command> [block]
  rule:
    description: Show the rules.
    aliases: [simplerule]
  pm:
    description: Private messages someone.
    aliases: [privatemsg]
    usage: /<command> <player> <message>
  killplayer:
    description: Kills a player.
    aliases: [destroyplayer]
    usage: /<command> <player>

permisssions:
  simpleplugin.*:
    description: Gives access to all the commands!
    default: op