name: SimplePlugin
main: io.github.lambo993.SimplePlugin
version: 0.7.4
authors: [Lambo993]
description: This is a very simple plugins.
commands:
  simpleplugin:
    description: Reloads simpleplugin.
    usage: /<command> <help/reload/version>
  ignite:
    description: Set a player on fire.
    aliases: [lighter]
    usage: /<command> <player> <seconds>
  hideme:
    description: Hide yourself from a player.
    aliases: [hidefrom]
    usage: /<command> <player>
  unhideme:
    description: Unhide yourself from a player.
  freeitem:
    description: Gives you a free item!
    usage: /<command> <item|numeric> [amount]
  freegift:
    description: Gives a player free item!
    usage: /<command> <player> <item|numeric> [amount]
  healthy:
    description: Heals you or the given player.
    aliases: [morehealth]
    usage: /<command> [player]
  generateblock:
    description: Generate a block on top of you!
    aliases: [blockgenerate]
    usage: /<command> <block> <weigth>
  rule:
    description: Show the rules.
    aliases: [simplerule]
    usage: /<command>
  pm:
    description: Sends a private message to the specified player.
    aliases: [privatemsg]
    usage: /<command> <player> <message>
  killplayer:
    description: Kills a player.
    aliases: [destroyplayer]
    usage: /<command> <player>
  explode:
    description: Explodes the target.
    aliases: [explosion]
    usage: /<command> <player>
  teleport:
    description: Teleports to the destination cords.
    usage: /<command> <x> <y> <z> [yaw] [pitch]
  teleportto:
    description: Teleports to the destination players.
    usage: /<command> <player> [player2]
  helmet:
    description: Sets the item in your hand as a hat.
    usage: /<command>
    aliases: [headgear]

permisssions:
  simpleplugin.*:
    description: Gives access to all the commands!
    default: op